language: cpp
sudo: required
dist: trusty
compiler:
  - gcc
  - clang
os:
  - linux
before_install:
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo sed -i -e 's/trusty/vivid/g' /etc/apt/sources.list && sudo apt-get update && sudo apt-get install -y cmake libeigen3-dev libgtest-dev; fi
script:
- ./build.sh
